### ISSUE TITLE
Onboarding: Set up payments task: display PayFast as an option for stores located in South Africa

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3596]
In the "Set up payments" step we need to display [PayFast](https://docs.woocommerce.com/document/payfast-payment-gateway/) as an option for stores located in South Africa. For this payment gateway we can adopt the same approach used for Klarna: install the extension and defer the configuration to the settings page.

**Comment by pmcpinto** [comment]
Hey @joshuatf I checked with the partnerships team and we need to highlight this gateway for stores located in SA. Let me know if you have any questions. Tks!

**Comment by timmyc** [comment]
Do we have a logo to display for Payfast?

**Comment by pmcpinto** [comment]
@timmyc we already display PayFast in the existing onboarding, so I'm assuming that we already have it. Let me know if I need to ask for it to the partnerships team.

**Comment by becdetat** [comment]
@pmcpinto I'm starting on this ticket. Is there any copy I should use for the plugin selection screen or should I just use the copy from the plugin?

**Comment by pmcpinto** [comment]
Hey @becdetat, considering that we need to implement some changes in this task (#3710), I'm not sure If this issues should be solved before that. What do you think?

cc @joshuatf for any additional feedback.

**Comment by becdetat** [comment]
@pmcpinto I only just saw your reply, I'm still getting some notification overload. Sorry about that. This is in review now, it's pretty self-contained though so if it can get in before #3710 is addressed I don't think it will be a problem.

I've just used the copy from the extension page (https://wordpress.org/plugins/woocommerce-payfast-gateway/).

**Comment by pmcpinto** [comment]
Hey @becdetat, no worries :)

Thanks for the heads up. Using the copy from the extension page seems to be a good option

**Comment by joshuatf** [comment]
>I'm still getting some notification overload.

Happens to most of us :)

>This is in review now, it's pretty self-contained though so if it can get in before #3710 is addressed I don't think it will be a problem.

Agreed, @becdetat.  We'll wait for #3738 to be merged before reworking the payments screen.
