### ISSUE TITLE
French - Uppercase with accent not displayed in new dashbard

### ISSUE THREAD

**Issue by gevcen** [woocommerce/woocommerce-admin#4282]
Dear,

As you can see in the below image, some letters are missing in the French titles. Please fix this.

"COMMANDES AVEC R**É**DUCTION"
"EXP**É**DITION"
"TAXE D’EXP**É**DITION"

![image](https://user-images.githubusercontent.com/51261962/80245846-b71d6100-866b-11ea-9842-cd0a36d8955e.png)

**Comment by juliaamosova** [comment]
My understanding that this issue had been fixed in https://github.com/woocommerce/woocommerce/pull/26339 because I can see that everything renders as expected when testing WC 4.1 rc.3:

![Screen Shot 2020-05-04 at 12 33 54 PM](https://user-images.githubusercontent.com/19143190/80993652-6e9f3980-8e09-11ea-8338-3aab778d3fbe.png)

**Comment by Savi-1** [comment]
No, it is not fixed. At least not in wooCommerce 4.1. The missing translations (which was another problem) are now shown correctly. 
This one is another issue as described in https://github.com/woocommerce/woocommerce-admin/issues/4311 (at least for the Czech and Slovak language).
This issue seems to be connected to the font used in WooCommerce Admin. It needs to support latin-extended letters/glyphs like "ščťžáé". Only blank spaces are where these letters should be shown. I've tested it on Czech and Slovak languages. 
<img width="1356" alt="Czech languagte missing letters" src="https://user-images.githubusercontent.com/65488451/82141418-fb98b880-9835-11ea-8845-4507226be8e4.png">

**Comment by vvvamik** [comment]
> 
> 
> No, it is not fixed. At least not in wooCommerce 4.1. The missing translations (which was another problem) are now shown correctly.
> This one is another issue as described in #4311 (at least for the Czech and Slovak language).
> This issue seems to be connected to the font used in WooCommerce Admin. It needs to support latin-extended letters/glyphs like "ščťžáé". Only blank spaces are where these letters should be shown. I've tested it on Czech and Slovak languages.
> <img alt="Czech languagte missing letters" width="1356" src="https://user-images.githubusercontent.com/65488451/82141418-fb98b880-9835-11ea-8845-4507226be8e4.png">

The problem still persists in version 4.3.1.

**Comment by timmyc** [comment]
The Summary Numbers have been re-designed to be more akin to the rest of the WordPress core styling, and part of this move was to update the font in use here, and no longer use all capitals. As such, I feel this bug is no longer present so I'm going to close this out. If anyone on the issue thread here is still experiencing this issue with WooCommerce 4.4, please do reply back. Thanks!

**Comment by vvvamik** [comment]
@timmyc In version 4.4.1. Unfortunately the problem still persists in the Czech language.

[url=https://ibb.co/f43PpQt][img]https://i.ibb.co/6gKfPNb/woo.jpg[/img][/url]

**Comment by Savi-1** [comment]
@timmyc the same in Slovak language. There is problem with latin-extended special letters/glyphs like "ščťžáé". The font needs to change to support latin-ext

**Comment by vvvamik** [comment]
@timmyc Update 4.6.1-  in Czech language problem solved.

**Comment by Savi-1** [comment]
@timmyc Update 4.6.1 - it's finally fixed in Slovak as well

**Comment by timmyc** [comment]
@vvvamik and @Savi-1 thanks for confirming the fix! I'll close this out now.
