### ISSUE TITLE
Activity panel appearing with incomplete setup tasks

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#5137]
**Describe the bug**
With the current core release (4.5.2) I'm seeing the activity panel (with Orders, Stock, and Reviews links) in the app bar on the home screen when the Setup tasks are still incomplete.

**To Reproduce**

1. Create a new test site and update to the latest release
2. Click on 'WooCommerce Home'
3. See error (activity panel appears)

**Expected behavior**
When store setup tasks haven't been completed and the setup card hasn't been dismissed, the activity panel should not appear on the Home screen.

**Screenshots**
<img width="1678" alt="Screen Shot 2020-09-13 at 8 47 34 PM" src="https://user-images.githubusercontent.com/5121465/93248091-f8b2c380-f754-11ea-831f-8b3891b0e885.png">

**Desktop (please complete the following information):**

* OS: Mac OS 10.15.6
* Browser: Firefox 80.0.1 and Chrome 85.0.4183.102

**Comment by samueljseay** [comment]
This is expected behaviour from the original spec (as far as I know, I implemented it this way on purpose).

The store setup link should not show on the home screen since the store setup list is displayed on that page.

**Comment by pmcpinto** [comment]
> This is expected behaviour from the original spec (as far as I know, I implemented it this way on purpose).
> The store setup link should not show on the home screen since the store setup list is displayed on that page.

I'm not finding the original spec, but the idea proposed by Elizabeth is to remove the activity panels from the home screen when the store setup task list is enabled. As most likely they still don't have any orders/products/reviews

**Comment by elizaan36** [comment]
Ah ok, I thought that was the original spec. 

> the idea proposed by Elizabeth is to remove the activity panels from the home screen when the store setup task list is enabled. As most likely they still don't have any orders/products/reviews

- Exactly, agree on this. Reducing the confusion of irrelevant links will help complete the store setup.
- Upon landing on the new Home screen experience, one of the first things that distracted me (when putting myself in the shoes of a new store owner) were the activity panel buttons. I was thinking, I won't have any of these things yet until I finish setup so why are the links persistent here?

**Comment by pmcpinto** [comment]
I'm going to label it with 1.6 as it would be good to ship it in this release. cc @timmyc

**Comment by samueljseay** [comment]
@pmcpinto @elizaan36 could you clarify, are you saying:

The activity panel should not be visible (just on the homescreen?) when the user is still progressing through the setup task list?

**Comment by elizaan36** [comment]
Hey Sam, 

> The activity panel should not be visible (just on the homescreen?) when the user is still progressing through the setup task list?

That's correct. We can simply remove the activity panel from the home screen while the initial store setup tasks are incomplete. Once required steps are complete, the activity panel will show.

As a side note I wanted to point out that we're eventually going to add logic so activity panel links would only appear when there's something new. This would solve the problem of making sure the activity panel doesn't disappear if a new task list item appears (in the case of extensions adding items to the task list), since the store may be further along and getting use out of the activity panel.

**Comment by samueljseay** [comment]
Sounds good, thanks!

**Comment by samueljseay** [comment]
@elizaan36 Could you confirm one more situation for me.

If you're performing a setup task currently (e.g. you click "Add my products" and it goes to the product setup screen) we just display the "help" item and the "store setup" link is not visible. Is that logic ok to keep or would you also like to display the store setup link while performing setup tasks?

**Comment by elizaan36** [comment]
hey, yeah it's ok to **not** show the "store setup" link and only show the "Help" item on the interstitial setup screens.

Though I am working on something separately to make the breadcrumb/back button more clear so it will be easier to get back from those screens.
