### ISSUE TITLE
Analytics > Settings - Blank Page

### ISSUE THREAD

**Issue by kingyyyyyy** [woocommerce/woocommerce-admin#6549]
Hi,

I have updated Woocommerce to the latest version on 2 websites. The only issue I've seen is that when you got to Analytics and then Settings, the page is blank, on both websites.

I have included two screenshots to show the issue.

Hope this helps.
![121212](https://user-images.githubusercontent.com/54516457/110556611-ca77d480-8136-11eb-84e9-72922981bfa0.png)
![1212133](https://user-images.githubusercontent.com/54516457/110556661-e24f5880-8136-11eb-84f4-8f81ee3184f7.png)

**Comment by psealock** [comment]
I can reproduce this. It appears to have been fixed in https://github.com/woocommerce/woocommerce-admin/pull/6540, but that won't make its way to WooCommerce until 5.2.

I can also downgrade to WP 5.6 and its working fine.

**Comment by kingyyyyyy** [comment]
Thanks for your replies. 

Is it fine for me to leave it as it is, until ver. 5.2, and not downgrade? 

And will the data from the new orders still populate the Analytics?

**Comment by becdetat** [comment]
Hi @kingyyyyyy 

It should be fine for you to wait for WooCommerce 5.2, and your new orders should still appear in analytics if you do wait.

We may release the fix as WooCommerce 5.2.1 so you could keep an eye out for it as well.

**Comment by splaquet** [comment]
We were having this issue as well, but on WordPress MultiSite.  Since I'm not seeing anyone reference that on this thread, I wanted to make sure that was also looked into and resolved.

It appears that when users with the SuperAdmin role do not also have an Admin role specifically set on a subsite, the blank page issue is present.  When we manually add the existing user to the site, with Admin permissions on the subsite, the content is again visible.

**Comment by becdetat** [comment]
@splaquet Is it just the analytics settings page that is going blank? Can you let us know the installed WordPress and WooCommerce versions?

**Comment by becdetat** [comment]
The issue has been fixed in the latest version of the [WooCommerce Admin plugin](https://wordpress.org/plugins/woocommerce-admin/). You can install the plugin over the top of WooCommerce and it will supersede the bundled WooCommerce Admin version included in WooCommerce. Then when the next version of WooCommerce is installed you can just remove the WooCommerce Admin plugin.

**Comment by becdetat** [comment]
@splaquet I'm particularly interested if installing the WooCommerce Admin plugin resolves your issue with a multisite configuration?

**Comment by splaquet** [comment]
@becdetat , it does appear as though upgrading woo-admin worked.  

BUT, while upgrading via CLI, I did receive this error (see screenshot) on one of our multisites.  My apologies, but I haven't looked any farther into error logs than the dashboard notice.  It did install though, because it network activated correctly on the second shot.

![image](https://user-images.githubusercontent.com/6146508/110725410-8f80aa00-81e5-11eb-8d40-b86353ebfd15.png)

**Comment by psealock** [comment]
Thanks @splaquet for confirmation of the fix and noting the error. 

I tried reproducing the error on updating wc-admin and was not able to. I will close this issue out but keep an eye out for the update error and create a new issue if it presents itself. Cheers

**Comment by fylgjur** [comment]
Issue encountered in the forums: https://wordpress.org/support/topic/analytics-not-showing/
I pointed the user to this issue report.

**Comment by fylgjur** [comment]
Also reported in 3820453-zen. I offered the workaround of installing Admin separately while we wait for an update.

**Comment by igotdes** [comment]
Encountered issue on 3857299-zen too. I've suggested the WooCommerce Admin plugin workaround.

**Comment by splaquet** [comment]
We're still seeing this issue, even after updating to the latest Woo & WooAdmin. 

At the time, we had resolution with the WooAdmin update. That was short lived, as the Woo update knocked it back out. 

Our workaround was adding SuperAdmins onto each subsite as Admins, but that's becoming annoying as more SuperAdmins request access. 

As well... 

I'm not sure if this is a plugin conflict or not (as we haven't stepped through plugin conflict troubleshooting), but... the latest Woo update not only knocked back Admin access, but now the Orders menu item does not display on the dashboard sidemenu. It's still available in the admin bar shortcut, but not listed under > WooCommerce menu.

**Comment by acafourek** [comment]
@splaquet 's comment helped solve this for me - I wasn't seeing any console errors but blank screen for all Analytics pages when logged in as a Super Admin. Explicitly adding Super Admin user to the site solved it for me.
